version: '3'
services:
  nuc: &nuc
    build: 
      context: .
      dockerfile: Dockerfile
    command: -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: passy 
    volumes:
      - nuc:/var/lib/postgresql/data
      - ./nuc/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./nuc:/nuc
      - initialbackup:/initialbackup
      - nucbackup:/nucbackup
    ports:
      - "9999:5432"
  cloud:
    <<: *nuc
    volumes:
      - initialbackup:/var/lib/postgresql/data
      - ./cloud/postgresql.conf:/etc/postgresql/postgresql.conf
      - nucbackup:/nucbackup
      - cloudbackup:/cloudbackup
    ports:
      - "8888:5432"
    expose:
      - '5432'
  subscriber:
    volumes:
      - subscriber:/var/lib/postgresql/data
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: passy 
    ports:
      - "7777:5432"
volumes:
  nuc:
  nucbackup:
  cloud:
  initialbackup:
  subscriber:
  cloudbackup:
