version: '3'
services:
  nuc: &nuc
    build: 
      context: .
      dockerfile: Dockerfile
    command: /nuc/start.sh
    environment:
      POSTGRES_PASSWORD: passy 
    volumes:
      - nuc:/var/lib/postgresql/data
      - ./nuc/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./nuc:/nuc
      - ./service-account-creds.json:/creds.json
      - nucbackup:/backup
    ports:
      - "9999:5432"
  cloud:
    <<: *nuc
    volumes:
      - ./cloud/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./nuc:/nuc
      - ./service-account-creds.json:/creds.json
      - nucbackup:/var/lib/postgresql/data
    ports:
      - "8888:5432"
volumes:
  nuc:
  nucbackup:
