version: '3'
services:
  nuc:
    image: postgres:13
    command: -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: passy 
    volumes:
      - nuc:/var/lib/postgresql/data
      - ./nuc.conf:/etc/postgresql/postgresql.conf
    expose:
      - "5432"
volumes:
  nuc:
